#!/usr/bin/env node

var resource = require('resource');
resource.use('github');
resource.logger.warn('getting activity, this may take a moment...');
resource.github.activity({ user: "marak" }, function (err, result){
  if (err) {
    throw err;
  }
  resource.logger.put(result);
});