#!/usr/bin/env node

var resource = require('resource');

resource.use('irc');

//
// Use the repl resource as a make-shift irc client for now
//
resource.use('repl');
resource.repl.start();

resource.irc.connect({
  host: 'irc.freenode.net',
  nick: 'resource-bot'
}, function (err, motd) {
  if (err) {
    throw err;
  }
  resource.irc.join({
    channel: '#resource'
  }, function (err, result) {
    console.log(err, result);
  });
});
