#!/usr/bin/env node

var resource = require('resource'),
    resources = require('resources');

resource.use('npm');

//
// Publishes all packages to npm
//

var keys = Object.keys(resources.resources);

function publish () {
  if (keys.length > 0) {
    var r = keys.pop(),
        path = './resources/' + r;
    resource.npm.publish(path, function (err, result) {
      publish();
    });
  }
}

publish();
