#!/usr/bin/env node

var resource = require('resource'),
    resources = require('resources');

resource.use('npm');

//
// Publishes all packages to npm
//

var keys = Object.keys(resources.resources);

function publish () {
  if (keys.length > 0) {
    var r = keys.pop(),
        _path = require('path').resolve(require.resolve('resources') + '/../' + r);
    resource.npm.publish(_path, function (err, result) {
      publish();
    });
  }
}

publish();
