#!/usr/bin/env node

var resource = require('resource');

resource.use('http');

resource.http.listen({ root: './' }, function(err, server) {
  var address = server.address();
  resource.logger.info('static server started on http://' + address.address + ":" + address.port)
});