#!/usr/bin/env node

var big = require('../big');

big.use('admin');

big.admin.start(function (err, server) {
  var address = server.address();
  big.logger.info('admin server started on http://' + address.address + ":" + address.port)
});
