#!/usr/bin/env node

var big = require('../big');

//
// Use the web admin resource
//
big.use('admin');

//
// Use the creature resource for demonstration purposes
//
big.use('creature', { datasource: "fs"});

big.admin.start(function (err, server) {
  var address = server.address();
  big.logger.info('admin server started on http://' + address.address + ":" + address.port)
});
