#!/usr/bin/env node

var big = require('../big');

//
// Log all events to console
//
big.onAny(function(data){
  big.logger.event(this.event.yellow);
});

big.use('resource', { datasource: 'fs' });
big.use('creature', { datasource: 'fs' });
big.use('http');
big.use('api');

big.http.start(function(err, server){
  var address = server.address();
  big.logger.info('api server started on http://' + address.address + ":" + address.port + "/api")
});
