#!/usr/bin/env node

var big = require('../big');
big.use('github');
big.logger.warn('getting activity, this may take a moment...');
big.github.activity({ user: "marak" }, function (err, result){
  if (err) {
    throw err;
  }
  big.logger.put(result);
});