#!/usr/bin/env node

var big = require('../big');

big.use('hook', { datasource: 'fs' });

var irc = big.use('irc');

big.resource.onAny(function(data){
  big.resource.logger.event(this.event.yellow);
});

big.hook.start(function (err) {
  irc.connect({
    channel: '#big'
  }, function (err, options) {
    if (err) {
      throw err;
    }
    big.resource.logger.put(options);
  }, function (err, _) {
  });
});
