#!/usr/bin/env node

var big = require('../big');

big.use('irc');

//
// Use the repl resource as a make-shift irc client for now
//
big.use('repl');
big.repl.start();

big.irc.connect({
  host: 'irc.freenode.net',
  nick: 'big-bot'
}, function (err, motd) {
  if (err) {
    throw err;
  }
  big.irc.join({
    channel: '#big'
  }, function (err, result) {
    console.log(err, result);
  });
});
