#!/usr/bin/env node

var big = require('../big');

big.use('hook', { datasource: 'fs' });
big.use('repl');

var irc = big.use('irc');

big.repl.start();

big.hook.start(function (err) {
  irc.connect({
    channel: '#big'
  }, function (err, options) {
    if (err) {
      throw err;
    }
    big.resource.logger.put(options);
  }, function (err, _) {
  });
});
