#!/usr/bin/env node

var big = require('../big');

big.use('http');
big.use('replicator');

big.http.start(function(err, server){
  big.replicator.start(function(err, server){
    if (err) {
      throw err;
    }
    console.log('replicator service listening on port ' + server.address().port);
  });
});
