#!/usr/bin/env node

var big = require('../big');

//
// Log all evens to console
//
big.resource.onAny(function(data){
  big.resource.logger.event(this.event.yellow);
});

big.use('admin');
big.use('irc');
big.use('creature');

big.admin.listen({ port: 8888 }, function (err, server){
  console.log(big.irc);
  console.log('slim-admin server started on http://localhost:8888/admin');
});
