#!/usr/bin/env node

var big = require('../big');

//
// Log all evens to console
//
big.resource.onAny(function(data){
  big.resource.logger.event(this.event.yellow);
});

big.use('admin');
big.use('hook', { datasource: 'fs'});

big.hook.start(function () {
  big.admin.listen({ port: 8888 }, function (err, server){
    console.log('slim-admin server started on http://localhost:8888/admin');
  });
});

