#!/usr/bin/env node

var big = require('../big');

big.use('http');

big.http.listen({ root: './' }, function(err, server) {
  var address = server.address();
  big.logger.info('static server started on http://' + address.address + ":" + address.port)
});