#!/usr/bin/env node

var big = require('../big'),
    twitter = big.use('twitter');

big.resource.onAny(function(data){
  big.resource.logger.event(this.event.yellow);
});

var log = big.resource.logger;

twitter.connect( {
  "consumer_key": "",
  "consumer_secret": "",
  "access_token_key": "",
  "access_token_secret": ""
}, function (err, options) {
  if (err) {
    log.error(err.errors);
    throw err;
  }
  twitter.send({
    message: 'hello friend'
  }, function (err, result) {
    if (err) {
      console.log(err.errors)
      throw err;
    }
    console.log(result);
  });
});

